/// Flutter icons LightDark
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  LightDark
///      fonts:
///       - asset: fonts/LightDark.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class LightDark {
  LightDark._();

  static const _kFontFam = 'LightDark';

  static const IconData theme_light_dark = const IconData(0xe801, fontFamily: _kFontFam);
}
